# Generated by Django 3.0.3 on 2020-02-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0006_auto_20200219_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
