# Generated by Django 3.0.3 on 2020-02-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0007_library_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='city',
        ),
        migrations.RemoveField(
            model_name='library',
            name='state',
        ),
        migrations.RemoveField(
            model_name='library',
            name='zip_code',
        ),
    ]
