# Generated by Django 3.0.3 on 2020-02-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0008_auto_20200220_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
