# Generated by Django 3.0.3 on 2020-03-03 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0012_library_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
