# Generated by Django 3.0.3 on 2020-03-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0013_auto_20200303_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
