# Generated by Django 3.0.3 on 2020-03-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0015_auto_20200303_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='libraries.Library'),
            preserve_default=False,
        ),
    ]
