# Generated by Django 3.0.3 on 2020-03-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0016_auto_20200303_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longtitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True),
        ),
    ]
