# Generated by Django 3.0.3 on 2020-03-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0018_auto_20200303_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
