# Generated by Django 3.0.3 on 2020-03-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0020_auto_20200304_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9, null=True),
        ),
    ]
