# Generated by Django 3.0.3 on 2020-03-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0022_auto_20200308_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='email',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
