# Generated by Django 3.0.3 on 2020-03-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0023_library_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='email',
            field=models.CharField(default='info@email.com', max_length=100),
        ),
    ]
