# Generated by Django 3.0.3 on 2020-03-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0024_auto_20200308_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='library',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='library',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
