# Generated by Django 3.0.3 on 2020-03-31 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0025_auto_20200310_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='review',
        ),
    ]
